### PR TITLE
simplify logic for baseline cam settings

### PR DESCRIPTION
**Pull request by bitterbark**
This should have that two line change in lib/CamDiag.py. Please advise if I need to change it!

Addresses #35

### CODE REVIEW

**Comment by nusbaume** [comment]
Thanks @bitterbark for the PR!  Can you make the following change to the comment on line 242 that I missed earlier, replacing:

`#Check if CAM baseline climatology files will be calculated:`

with

`#Check if a CAM vs CAM baseline comparison is being performed:`

You can add that change to this PR by simply making the modification in your local copy of your logic_baseline_cam_settings branch, committing it, and then pushing it back to your fork.  Once that is done I'll go ahead and approve and merge the PR.  Thanks!

**Comment by nusbaume** [comment]
Hi @bitterbark 

Sorry, I realized there is one more change I missed.  Can you replace the code on line 248:

`self.__expand_references(self.__cam_climo_info, config_search_dict)`

with

`self.__expand_references(self.__cam_bl_climo_info, config_search_dict)`

Once that is done I will go ahead and merge it (for real this time).  Thanks again!

**Comment by bitterbark** [comment]
Sorry about that--what I get for not testing it last time. It runs now for me.

**Review by nusbaume — APPROVED** [review]
Looks great now, thanks!

**Pull request merged**
